SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `candy`
--

-- --------------------------------------------------------

--
-- articles
--

CREATE TABLE IF NOT EXISTS `articles` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `author` varchar(255) NOT NULL,
  `content` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=9 ;

--
-- articles
--

INSERT INTO `articles` (`id`, `author`, `content`) VALUES
(1, 'Yonas', '\r\n\r\nBacon ipsum dolor amet ground round jowl kevin cupim shankle sirloin chuck. Ham capicola picanha, spare ribs short ribs rump tri-tip venison landjaeger short loin shoulder strip steak. Meatloaf andouille frankfurter tri-tip venison flank pig ground round sausage. Drumstick capicola turkey ham salami hamburger jowl meatloaf rump. Pork chop meatball salami brisket shank ham hock andouille bacon bresaola ribeye chicken ham fatback kevin tenderloin. Swine pancetta turkey, meatball ham pork tri-tip short loin ham hock pork belly chuck. Shank capicola beef andouille frankfurter pork loin tongue kevin alcatra jowl turducken pancetta rump cow.\r\n\r\nPancetta pork belly corned beef ham shoulder cupim pork loin. Pork loin turducken picanha spare ribs swine fatback cupim chicken. Bresaola pork chop pancetta, cupim pork prosciutto shoulder landjaeger ribeye biltong turducken beef. Meatloaf flank ground round, pork ham hock ham meatball fatback. Pork strip steak pig fatback, shankle shank meatloaf boudin turducken biltong kielbasa short ribs prosciutto.\r\n\r\nFrankfurter venison prosciutto corned beef pork belly shankle. Kevin drumstick boudin, alcatra turducken pork belly picanha frankfurter cow. Short loin pancetta pig salami venison turkey shankle shoulder. Porchetta sirloin meatloaf tenderloin cow kevin prosciutto doner pork landjaeger. Chicken boudin andouille, beef ribs rump kielbasa tri-tip chuck pork belly. Kielbasa sirloin fatback frankfurter ham turkey cupim, pancetta porchetta brisket shankle pork belly sausage ham hock. T-bone fatback landjaeger, sausage biltong corned beef cupim cow short ribs.\r\n\r\nShoulder salami jowl ham hock sausage turkey prosciutto capicola swine chicken short loin kevin hamburger beef. Tongue turducken filet mignon t-bone. Sirloin tail pork loin pancetta pork chop frankfurter ham hock. Venison pastrami brisket, meatloaf shank picanha pork belly boudin chicken tail. Spare ribs porchetta jerky, meatloaf filet mignon shoulder beef ribs alcatra chuck pig flank meatball chicken ground round. Tail chuck jowl salami pig chicken. Landjaeger pork loin t-bone short loin, hamburger tenderloin boudin pork belly brisket picanha.\r\n\r\nCupim pork loin drumstick, strip steak sirloin pig shank brisket tenderloin fatback tongue meatloaf. Doner chicken shank shoulder, sirloin pork porchetta ham strip steak short ribs jowl boudin kielbasa. Tail andouille short loin rump pancetta kielbasa beef meatloaf filet mignon picanha salami t-bone. Strip steak t-bone jowl short loin chicken. Beef sirloin short loin pastrami hamburger. Andouille kielbasa corned beef shank short loin picanha.'),
(2, 'Obama', 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.'),
(3, 'Jason', '\r\n\r\nBacon ipsum dolor amet kielbasa strip steak pancetta, cow leberkas pork ham. Drumstick frankfurter sirloin filet mignon shankle. Pastrami leberkas tri-tip porchetta, landjaeger chuck salami venison rump. Jerky pork belly shoulder, turkey meatball shank pancetta strip steak rump picanha doner corned beef.\r\n\r\nFatback swine capicola, tail pork jerky turducken shankle doner kielbasa. T-bone ground round beef ribs, corned beef rump turkey pig ham boudin flank ball tip. Tail biltong swine pastrami pork chop landjaeger turducken. Ham hock chuck picanha pancetta turkey beef ribs, tongue kielbasa brisket.\r\n\r\nBacon short loin ham salami landjaeger tongue picanha doner ham hock rump meatloaf chuck. Pork chop drumstick tongue, corned beef capicola sirloin shoulder boudin jowl chuck strip steak kielbasa. Venison ground round cow spare ribs bresaola sirloin filet mignon chuck picanha drumstick. Beef ribs picanha spare ribs doner pastrami tongue cupim. Pork belly cupim pig, sausage short loin turkey t-bone sirloin turducken. Biltong tenderloin t-bone pancetta meatball flank bresaola short ribs ham. Turkey chuck jowl frankfurter shoulder short loin capicola bresaola chicken alcatra.\r\n\r\nFrankfurter leberkas pastrami, venison tri-tip porchetta tail pancetta capicola short ribs ball tip. Fatback venison porchetta tongue, chuck frankfurter cow filet mignon rump sausage doner jowl. Picanha porchetta pork belly, swine pancetta jowl ground round tenderloin pork. Pig doner t-bone porchetta prosciutto cow biltong frankfurter brisket tongue rump tenderloin beef ribs alcatra.\r\n\r\nDoner capicola venison pork chop cow, turducken prosciutto pastrami swine. Pancetta spare ribs tail swine prosciutto shank kielbasa short ribs chicken ground round pig jowl. Fatback bacon tongue short loin sirloin pork. Swine sirloin ground round venison picanha turducken leberkas tongue.'),
(4, 'James', 'Bacon ipsum dolor amet shoulder filet mignon pork belly tri-tip rump, drumstick capicola andouille. Ball tip boudin chicken strip steak. Short loin picanha sirloin beef ham alcatra jowl flank. Kielbasa pastrami shankle, ham hock ribeye jerky corned beef sirloin. Pastrami tongue hamburger spare ribs turducken. Ball tip alcatra beef ribs jerky short loin, beef tenderloin pork loin biltong bresaola ham hock. Ball tip beef meatball, doner sirloin drumstick meatloaf cow pork loin.\r\n\r\nBoudin pork sirloin fatback corned beef, kielbasa frankfurter hamburger doner tongue ham hock. Beef ribs pig sausage sirloin. Pork sausage picanha prosciutto tail shank capicola. Ham hock biltong short ribs short loin cow.\r\n\r\nBrisket pork chop flank jowl pork belly bresaola pig hamburger. Cupim beef boudin porchetta ham hamburger picanha tongue filet mignon meatball t-bone biltong meatloaf doner. Alcatra pork ham chicken ball tip. Spare ribs capicola frankfurter pork belly drumstick leberkas. Doner meatball tri-tip capicola cupim.\r\n\r\nCupim flank beef ribs porchetta rump. Frankfurter ham hock capicola hamburger. Beef tongue bacon, tri-tip ham hock kevin turducken. Venison jerky boudin, beef salami tenderloin biltong prosciutto bresaola swine. Corned beef porchetta swine, boudin frankfurter venison bresaola. Sausage porchetta jowl picanha meatloaf brisket pancetta cow landjaeger hamburger cupim bacon pork belly fatback shank.\r\n\r\nAlcatra hamburger turkey andouille pancetta venison, short ribs ham frankfurter ham hock kevin swine shankle short loin cow. Short ribs pork chop pork belly venison, frankfurter doner turducken chuck capicola chicken kielbasa sausage. Ribeye cupim jerky tongue. Ball tip turkey filet mignon porchetta flank picanha. Tri-tip bresaola flank, porchetta tail fatback strip steak tenderloin brisket beef venison chicken. Turkey pig spare ribs pork chop pastrami bresaola sirloin doner sausage tri-tip jowl pancetta ham hock andouille frankfurter.'),
(5, 'Jackson', '\r\n\r\nBacon ipsum dolor amet ham hock porchetta frankfurter pork loin boudin prosciutto. Swine tongue strip steak brisket sirloin shank. Pastrami chuck turducken pork chop jerky flank. T-bone pork fatback brisket corned beef ribeye. Pig landjaeger chuck, ribeye doner flank turducken.\r\n\r\nAndouille meatloaf tongue, tri-tip pork chicken frankfurter fatback flank. Tongue strip steak filet mignon short loin kielbasa sirloin. Short ribs beef ribs pancetta landjaeger salami cupim tongue cow pork loin chuck pork chop t-bone ribeye tail porchetta. Shoulder rump beef ball tip turkey pork chicken pork chop ribeye alcatra. Meatball beef bacon strip steak short ribs meatloaf ball tip pig pastrami picanha kevin short loin biltong bresaola drumstick.\r\n\r\nPig tail short loin bresaola, pork chop picanha meatball pork belly drumstick tongue spare ribs swine. Turducken pastrami salami, pancetta biltong boudin jowl tenderloin ribeye alcatra short ribs chicken shank filet mignon. Turkey meatball corned beef filet mignon. Salami pastrami drumstick pancetta short ribs tri-tip, frankfurter porchetta fatback sausage bresaola kevin ham swine pig.\r\n\r\nAlcatra ground round pork loin, short loin bacon drumstick corned beef strip steak meatloaf frankfurter pork belly venison fatback ribeye hamburger. Spare ribs biltong tail swine, shank chicken kielbasa t-bone sausage tri-tip ribeye corned beef. Beef strip steak brisket prosciutto, venison porchetta capicola tail hamburger sirloin andouille leberkas kevin pork. Ground round pastrami biltong frankfurter short loin, meatball pork pork chop fatback andouille kevin picanha drumstick flank jowl.\r\n\r\nSausage corned beef pork kielbasa, rump turkey tri-tip ham hock pig leberkas biltong jowl andouille tenderloin landjaeger. Tail picanha kielbasa fatback alcatra shank shankle pastrami andouille pork loin kevin flank rump meatloaf cow. Turducken ball tip drumstick t-bone meatloaf tail cupim hamburger. Alcatra cow ham flank, jowl swine leberkas meatball. Turducken cow sausage beef ribs pastrami jowl.'),
(6, 'Born', '\r\n\r\nBacon ipsum dolor amet sirloin biltong cupim cow ribeye kevin fatback ball tip rump salami pork chop picanha ground round ham hock. Doner alcatra beef picanha shank flank tail pork belly ham porchetta ground round beef ribs short ribs meatball andouille. Landjaeger short ribs jowl sausage shank pork picanha beef ribs leberkas tongue shoulder rump. Flank fatback chicken pastrami, pork belly short ribs swine ham hock salami prosciutto. Swine pancetta jerky, cow short ribs alcatra jowl ham spare ribs. Shoulder hamburger andouille, corned beef cow t-bone meatball landjaeger spare ribs jerky porchetta pork chop shank boudin tongue. Jerky turducken hamburger frankfurter ribeye bacon capicola, bresaola rump kevin.\r\n\r\nHamburger shank beef, rump shoulder tongue cow. Bresaola beef alcatra capicola ribeye leberkas shankle pork belly tongue jerky ground round turducken porchetta. Pork belly flank turkey capicola pancetta turducken andouille short loin. T-bone landjaeger tenderloin shankle, pork loin beef ribs pig doner. Chuck shank cow hamburger beef ribs brisket andouille. Ham pork belly corned beef strip steak, flank leberkas spare ribs cow bacon hamburger bresaola. Salami tenderloin pastrami, ribeye pork chop hamburger tongue pork loin.\r\n\r\nCapicola boudin venison prosciutto, jowl chicken bresaola andouille landjaeger. Pig prosciutto bresaola, tail meatloaf beef ribs ground round fatback jerky shoulder picanha. Biltong frankfurter doner landjaeger short ribs, hamburger kevin turkey leberkas. Pastrami pancetta pork chop flank kielbasa pork belly. Biltong t-bone chicken landjaeger meatloaf, shoulder porchetta hamburger cupim capicola doner kielbasa tenderloin. Pastrami alcatra ground round leberkas landjaeger sausage turkey bresaola tongue filet mignon.\r\n\r\nBeef biltong alcatra porchetta pork ham frankfurter shank cow. Filet mignon t-bone salami landjaeger ham hock flank, frankfurter shankle pork loin shank leberkas ball tip chicken corned beef beef ribs. Ham biltong andouille hamburger, venison pancetta turkey salami. Jerky chuck bresaola flank turducken picanha. Pastrami jowl frankfurter fatback t-bone tri-tip turkey ground round shank ham hock beef turducken kevin ball tip andouille. Meatloaf brisket salami pork loin chuck, venison beef ribs alcatra ribeye prosciutto beef.\r\n\r\nHam ribeye beef, frankfurter sausage andouille shank. Meatloaf turkey ball tip chuck pork belly cupim, pork chop short ribs shankle filet mignon shank bacon fatback salami. Beef ribs chuck pastrami, corned beef frankfurter beef capicola t-bone sausage tail doner chicken ground round short ribs. Turducken andouille leberkas, short ribs spare ribs biltong alcatra chuck fatback tail pancetta turkey cupim. Meatloaf doner ribeye tenderloin frankfurter.'),
(7, 'Artist', '\r\n\r\nBacon ipsum dolor amet spare ribs hamburger tongue pork loin brisket pork, biltong beef ribs cow kevin strip steak ribeye tail pork belly. Tongue tri-tip chuck, tail short ribs shank beef ribs turducken short loin bresaola shoulder. Beef fatback beef ribs, tongue doner tri-tip pork belly capicola ribeye. Chicken bresaola brisket, ball tip cow kielbasa shoulder shank ham hamburger prosciutto spare ribs tenderloin capicola. Pancetta porchetta prosciutto tail t-bone rump. Sirloin boudin t-bone swine. Ground round venison ham ribeye.\r\n\r\nFlank beef leberkas shank sirloin ground round frankfurter chicken short ribs pig ribeye pork belly pork. Tenderloin boudin ball tip shoulder pork, chicken drumstick alcatra tri-tip beef ribs. Drumstick jerky venison bacon tenderloin pastrami ribeye, kielbasa sirloin pancetta cupim strip steak pork loin capicola fatback. Hamburger porchetta shankle, ham shank t-bone chicken capicola jerky meatball spare ribs. Shankle ham hock turducken doner pastrami. Hamburger pork belly picanha landjaeger alcatra short ribs tri-tip kevin beef turducken. Short loin corned beef brisket, hamburger salami kielbasa fatback swine.\r\n\r\nTongue t-bone pig shankle meatball shank hamburger shoulder tail ground round corned beef chicken. Salami shankle andouille pork chop doner prosciutto pancetta. Ground round tail chuck shoulder bacon biltong venison short ribs drumstick pork loin t-bone bresaola ham hock alcatra. Andouille brisket fatback rump. Capicola tail cupim, bresaola shoulder salami shankle biltong meatball pastrami strip steak bacon pork. Kevin flank salami chuck meatball drumstick.\r\n\r\nLandjaeger meatball turkey, pork belly beef tri-tip ham tongue swine porchetta kevin alcatra pig pancetta. Leberkas bresaola jerky, bacon jowl pork chuck shoulder. Pork chop fatback alcatra tail flank leberkas, landjaeger shank filet mignon ham hock corned beef kielbasa ham. Beef andouille shank doner rump, kielbasa swine sirloin. Turkey ham venison, picanha swine cupim turducken tongue kevin boudin ball tip.\r\n\r\nTurducken pastrami rump meatloaf cupim pork belly prosciutto shoulder pork loin pork pork chop porchetta leberkas meatball. Frankfurter meatball drumstick shank jerky, pork loin ground round sirloin. Pork belly salami tongue, sirloin meatball landjaeger cupim frankfurter. Jerky jowl ground round, sausage prosciutto short ribs hamburger. Short ribs tongue chuck ham shank, prosciutto biltong fatback filet mignon tail swine flank. Alcatra chuck leberkas, swine picanha ground round biltong boudin prosciutto turducken chicken jerky beef.'),
(8, 'Musican', '\r\n\r\nBacon ipsum dolor amet pig pork pork chop pastrami beef ribs venison. Tail pork belly turkey ball tip prosciutto ribeye. Picanha shankle venison bresaola, turducken shoulder tongue jerky strip steak andouille brisket landjaeger pancetta prosciutto pastrami. Andouille meatball rump shankle kielbasa. Jowl strip steak tongue, swine turkey hamburger boudin tri-tip tenderloin.\r\n\r\nProsciutto pancetta andouille ribeye sirloin pork chop alcatra tongue picanha drumstick short loin shankle bresaola. Pork chop alcatra rump cupim, turkey corned beef salami ribeye filet mignon. T-bone ribeye meatball strip steak, picanha drumstick capicola. Brisket ham turducken tenderloin ball tip shoulder. Hamburger pastrami prosciutto, tail spare ribs brisket drumstick kielbasa ham hock tongue cow shoulder sirloin bresaola. Picanha tongue jowl sausage meatball. Shoulder fatback porchetta salami drumstick filet mignon tongue corned beef kielbasa leberkas beef ribs tenderloin short loin.\r\n\r\nLeberkas tongue pastrami shank, shoulder pancetta meatball jowl bresaola chuck. Frankfurter kevin shank, short ribs turducken pancetta sirloin shankle beef picanha meatball prosciutto. Ribeye pork bacon filet mignon, meatball alcatra tri-tip tail flank tongue beef. Beef jerky tail, swine cupim ham hock shank. Rump pancetta cow shank ball tip shoulder swine bresaola tenderloin turducken kevin jowl t-bone prosciutto doner. Alcatra strip steak chicken shoulder. Chicken short loin andouille tri-tip boudin bacon brisket spare ribs landjaeger sirloin ribeye sausage frankfurter.\r\n\r\nBacon pork loin pancetta porchetta, ball tip jowl prosciutto bresaola boudin shank shoulder. Ham porchetta shank tenderloin andouille tongue pancetta sausage kielbasa pork biltong capicola tri-tip cow t-bone. Tri-tip capicola fatback kevin swine andouille pork belly picanha short loin jerky turducken t-bone tail shank meatball. Alcatra bresaola pig doner rump. Doner shank sirloin boudin strip steak shoulder cow cupim alcatra prosciutto. Shank boudin brisket jowl ham venison pork belly pig bresaola capicola andouille sausage. Tenderloin shankle pork chop alcatra biltong spare ribs tongue shoulder tri-tip jowl kielbasa swine brisket t-bone.\r\n\r\nCow doner ham hock filet mignon, cupim prosciutto tail jowl shankle drumstick chicken ground round short loin andouille. Drumstick short loin cupim beef alcatra. Short loin beef ribs meatloaf salami. Picanha beef jerky pancetta rump chuck tail brisket jowl tri-tip prosciutto. Flank brisket kevin corned beef porchetta salami chicken. Fatback meatball strip steak flank, tri-tip alcatra spare ribs biltong boudin.');

-- --------------------------------------------------------

--
-- users
--

CREATE TABLE IF NOT EXISTS `users` (
  `name` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
